target-version = "py312"

# Exclude specific rules
ignore = [
    "D203",  # 1 blank line required before class docstring
    "D212",  # Multi-line docstring summary should start at the first line
]

line-length = 100
