name: Deploy Prefect Flow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GCP_REGION: '${{ secrets.GCP_REGION }}'
  GCP_PROJECT: '${{ secrets.GCP_PROJECT_ID }}'
  ARTIFACT_REGISTRY: '${{ secrets.GCP_ARTIFACT_REGISTRY }}'
  IMAGE_NAME: '${{ secrets.IMAGE_NAME }}'
  IMAGE_TAG: latest
  PREFECT_API_KEY: '${{ secrets.PREFECT_API_KEY }}'
  PREFECT_API_URL: 'https://api.prefect.cloud/api/accounts/${{ secrets.PREFECT_ACCOUNT_ID }}/workspaces/${{ secrets.PREFECT_WORKSPACE_ID }}'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}
    
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        pip install prefect prefect-docker
    
    - name: Deploy Prefect Flow
      uses: PrefectHQ/actions-prefect-deploy@v3
      env:
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        PREFECT_API_URL: ${{ env.PREFECT_API_URL }} 