name: Deploy Prefect Flow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GCP_REGION: '${{ secrets.GCP_REGION }}'
  GCP_PROJECT: '${{ secrets.GCP_PROJECT_ID }}'
  ARTIFACT_REGISTRY: '${{ secrets.GCP_ARTIFACT_REGISTRY }}'
  IMAGE_NAME: '${{ secrets.IMAGE_NAME }}'
  IMAGE_TAG: latest
  PREFECT_API_KEY: '${{ secrets.PREFECT_API_KEY }}'
  PREFECT_API_URL: 'https://api.prefect.cloud/api/accounts/${{ secrets.PREFECT_ACCOUNT_ID }}/workspaces/${{ secrets.PREFECT_WORKSPACE_ID }}'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Enable Docker BuildKit
      run: |
        echo '{"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        driver-opts: image=moby/buildkit:latest
    
    - name: Configure Docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install "prefect>=3.1.15,<4.0.0"
        uv pip install "prefect-docker>=0.6.2"
        uv sync --all-extras
    
    - name: Deploy Prefect Flow
      uses: PrefectHQ/actions-prefect-deploy@v3
      with:
        deployment-names: market_data_ingestion
        deployment-file-path: ./prefect.yaml
      env:
        DOCKER_BUILDKIT: "1"
        COMPOSE_DOCKER_CLI_BUILD: "1"
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        PREFECT_API_URL: ${{ env.PREFECT_API_URL }}
        PATH: ${{ github.workspace }}/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 